name: video_player_avfoundation
description: iOS implementation of the video_player plugin.
repository: https://github.com/dungngminh/adjusted_video_player_avfoundation
version: 2.4.6

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

flutter:
  plugin:
    implements: video_player
    platforms:
      ios:
        dartPluginClass: AVFoundationVideoPlayer
        pluginClass: FLTVideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface: ">=6.1.0 <7.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^9.2.4
